name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2024
          sync: false
          use_insecure_cipher: false
          timeout: 30s
          command_timeout: 10m
          script_stop: false
          debug: true  # Enable debug for more detailed logs

      - name: Debug SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no root@123.108.97.5 -p 2024 "echo 'SSH connection successful'"

      - name: Deploy application
        run: |
          ls /root/
