name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2024
          script: |
            # Create a temporary directory
            TEMP_DIR=$(mktemp -d)
            # Copy the repository to the temporary directory
            git clone $GITHUB_REPOSITORY $TEMP_DIR
            # Remove the existing content in the /www/ directory
            sudo rm -rf /www/*
            # Copy the new content to the /www/ directory
            sudo cp -R $TEMP_DIR/* /www/
            # Change the ownership to www user
            sudo chown -R www:www /www/
            # Clean up the temporary directory
            rm -rf $TEMP_DIR
            sudo ls -laht /www/
